### ISSUE TITLE
Request to add references for the formulas used in the code

### ISSUE THREAD

**Issue by dinoue-bryophyta** [kantner/LaserNoise#1]
Hi,

It's a very impressive code. 
Could you please provide the reference papers or books for the formulas used?"

Thank you.

**Comment by kantner** [comment]
Hi!
Sorry for the late reply. I have overlooked your request. Please take a look on our paper in Optics Express for the laser model:
https://doi.org/10.1364/OE.485866

**Comment by dinoue-bryophyta** [comment]
Hi, great thanks.
